tecla_w = "W             Andar para cima";
tecla_a = "A             Andar para a esquerda";
tecla_s = "S             Andar para baixo";
tecla_d = "D             Andar para a direita";
tecla_m = "M             Pausa o áudio do jogo";
tecla_shift = "Shift          Faz andar mais rápido";
tecla_r = "R             Interação com os NPC's";
tecla_space = "Space          Passa os diálogos e seleciona a opção nas missões";
tecla_setas = "Setas          Mudam a seleção das opções nas missões";